
CREATE TABLE `data` (
  `id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `image` varchar(50) NOT NULL,
  `task` varchar(100) NOT NULL,
  `description` longtext CHARACTER SET utf8 NOT NULL,
  `category` varchar(5) NOT NULL,
  `status` int(3) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


INSERT INTO `data` (`id`, `name`, `image`, `task`, `description`, `category`, `status`) VALUES
(1, 'Renjana A R', '53.jpg', 'Marketting', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(2, 'Abhishek V A, Anandhu M B, Darsan Dilip & Johan T R', '2.jpg,7.jpg,14.jpg,49.jpg', 'Aripodi', 'Nallat Cheytaal', 'G4', 0),
(3, 'Ajaya Krishnan', '4.jpg', 'Treasure Hunt', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(4, 'Sruthy N V', '29.jpg', 'Favourite Senior', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(5, 'Rahul M M, Abhishek S, Amal Joseph, Anandhu Suresh & Vishal Thomas ', '24.jpg,32.jpg,34.jpg,36.jpg,59.jpg', 'Fashion Show', 'Nallat Cheytaal, Nallat Kittum', 'G5', 0),
(6, 'Sidharth T S', '28.jpg', 'Dubsmash', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(7, 'Vishnu K Saji', '60.jpg', 'Proposing Teacher', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(8, 'Jevin J Thomas & Reenu Maria Binoy', '48.jpg,52.jpg', '', 'Nallat Cheytaal, Nallat Kittum', 'G2', 0),
(9, 'Kavyamol P S', '51.jpg', 'Spot Dance', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(10, 'Manasi S, Parvathy Prakash & Abhirami Prakash', '21.jpg,23.jpg,31.jpg', 'Juice Filling', 'Nallat Cheytaal, Nallat Kittum', 'G3', 0),
(11, 'Joseph Thomas', '50.jpg', 'Bathing', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(12, 'Dayana Thomas', '15.jpg', 'Tapas Elakkal', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(13, 'Shahana M S, Aneesha Antony & Anagha R', '27.jpg,37.jpg,35.jpg', 'Cookery Emotion', 'Nallat Cheytaal, Nallat Kittum', 'G3', 0),
(14, 'Ashok Anil', '40.jpg', 'Counter', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(15, 'Varghese Thomas', '57.jpg', 'Outdoor Task', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(16, 'Akhila S Nair, Archana K Shaji, Sachu Paul Thomas & Savio Francis', '5.jpg,9.jpg,54.jpg,55.jpg', 'Margamkali', 'Nallat Cheytaal, Nallat Kittum', 'G4', 0),
(17, 'Devika Babu', '17.jpg', 'Mimicry', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(18, 'Jerin Joseph', '47.jpg', 'Balloon + Glass', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(19, 'Aswin Saji, Bibin Moncy, Nithin Raj & James Mathew', '11.jpg,12.jpg,22.jpg,45.jpg', 'Margamkali', 'Nallat Cheytaal, Nallat Kittum', 'G4', 0),
(20, 'Chris Sosa Jacob', '13.jpg', 'Biscuit', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(21, 'Sanju S Pillai', '26.jpg', 'Driving', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(22, 'Ashik N S, Deepak Scaria S, Rose Sara Saji & Devika Baiju', '10.jpg,16.jpg,25.jpg,42.jpg', 'Paper Dance', 'Nallat Cheytaal, Nallat Kittum', 'G4', 0),
(23, 'Aryadevi C S', '39.jpg', '', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(24, 'Lijo Xavier', '19.jpg', 'Body Show', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(25, 'Suvarna Jany, Adithya Suresh & Sreya James', '30.jpg,33.jpg,56.jpg', 'Balloon Dance', 'Nallat Cheytaal, Nallat Kittum', 'G3', 0),
(26, 'Haripriya R Nair', '44.jpg', 'Banana Song', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(27, 'James Thomas', '46.jpg', 'Card', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(28, 'Bibin Joseph & Vimel Manoj', '41.jpg,58.jpg', 'Pachamulaku + Kuppi', 'Nallat Cheytaal, Nallat Kittum', 'G2', 0),
(29, 'Alphiya Yunoose', '6.jpg', 'Boozer', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(30, 'Anu Joseph', '38.jpg', 'Kalippante Kanthari', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(31, 'Livin Anna Varghese & Devika R Nath', '20.jpg,43.jpg', 'Mouth Water Speech', 'Nallat Cheytaal, Nallat Kittum', 'G2', 0),
(32, 'Aravind Santhosh', '8.jpg', 'Cello Tape', 'Nallat Cheytaal, Nallat Kittum', 'I', 0),
(33, 'Abhilash Mathew, Adarsh Santhosh & Gokul Prakash', '01.jpg,3.jpg,18.jpg', 'Balloon Sitting', 'Nallat Cheytaal, Nallat Kittum', 'G3', 0);